### Librerias

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import holidays
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

from functools import partial# import ace_tools as tools

### Directorios

In [2]:
DATOS_DIR = '../data/'
SALIDAS_DIR = '../salidas/'

Lectura de datos

In [3]:
FILE_NAME_INPUT='sell_in_03-featureaddv1.parquet"'

df = pd.read_parquet(SALIDAS_DIR + FILE_NAME_INPUT)

In [6]:
df.info()
df.head(40)

<class 'pandas.core.frame.DataFrame'>
Index: 16422912 entries, 0 to 16215443
Data columns (total 39 columns):
 #   Column                 Dtype
---  ------                 -----
 0   customer_id            int32
 1   product_id             int32
 2   plan_precios_cuidados  int8
 3   cust_request_qty       float32
 4   cust_request_tn        float32
 5   tn                     float32
 6   cat1                   category
 7   cat2                   category
 8   cat3                   category
 9   brand                  category
 10  sku_size               int32
 11  periodo_indice         int16
 12  year                   int16
 13  month                  int8
 14  quarter                int8
 15  month_idx              int32
 16  is_fy_start            int8
 17  is_fy_end              int8
 18  season                 category
 19  mes_anormal_1          int8
 20  mes_anormal_2          int8
 21  clase                  float32
 22  tn-1                   float32
 23  tn-2                   float32
 24  tn-3                   float32
 25  tn-4                   float32
 26  tn-5                   float32
 27  tn-6                   float32
 28  tn-7                   float32
 29  tn-8                   float32
 30  tn-9                   float32
 31  tn-10                  float32
 32  tn-11                  float32
 33  tn_roll_mean_3         float32
 34  tn_roll_std_3          float32
 35  tn_roll_mean_6         float32
 36  tn_roll_std_6          float32
 37  tn_roll_mean_12        float32
 38  tn_roll_std_12         float32
dtypes: category(5), float32(21), int16(2), int32(4), int8(7)
memory usage: 1.9 GB

,customer_id,product_id,plan_precios_cuidados,cust_request_qty,cust_request_tn,tn,cat1,cat2,cat3,brand,...,tn-8,tn-9,tn-10,tn-11,tn_roll_mean_3,tn_roll_std_3,tn_roll_mean_6,tn_roll_std_6,tn_roll_mean_12,tn_roll_std_12
0,10001,20001,0,11.0,99.438606,99.438606,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,10001,20001,0,23.0,198.843643,198.843643,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,10001,20001,0,33.0,92.465370,92.465370,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,10001,20001,0,8.0,13.297280,13.297280,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,130.249207,59.506756,0.000000,0.000000,0.000000,0.000000
4,10001,20001,0,15.0,101.207108,101.005630,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,101.535431,93.105118,0.000000,0.000000,0.000000,0.000000
5,10001,20001,0,25.0,128.047913,128.047913,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,68.922760,48.361965,0.000000,0.000000,0.000000,0.000000
6,10001,20001,0,18.0,101.207108,101.207108,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,80.783607,59.988537,105.516411,59.915985,0.000000,0.000000
7,10001,20001,0,17.0,43.339298,43.339298,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,110.086884,15.555034,105.811157,59.884445,0.000000,0.000000
8,10001,20001,0,36.0,289.350250,289.350250,HC,ROPA LAVADO,Liquido,ARIEL,...,99.438606,NaN,NaN,NaN,90.864777,43.290997,79.893768,42.774193,0.000000,0.000000
9,10001,20001,0,22.0,222.113892,222.113892,HC,ROPA LAVADO,Liquido,ARIEL,...,198.843643,99.438606,NaN,NaN,144.632217,128.626022,112.707916,96.334335,0.000000,0.000000
10,10001,20001,0,20.0,114.011902,111.549438,HC,ROPA LAVADO,Liquido,ARIEL,...,92.465370,198.843643,99.438606,NaN,184.934479,127.149826,147.510681,90.797928,0.000000,0.000000
11,10001,20001,0,19.0,131.271500,131.271500,HC,ROPA LAVADO,Liquido,ARIEL,...,13.297280,92.465370,198.843643,99.438606,207.671188,89.775978,149.267990,89.814568,0.000000,0.000000
12,10001,20001,0,26.0,49.618568,49.618568,HC,ROPA LAVADO,Liquido,ARIEL,...,101.005630,13.297280,92.465370,198.843643,154.978271,58.971458,149.805252,89.671768,127.660828,76.300400
13,10001,20001,0,16.0,92.137352,88.440651,HC,ROPA LAVADO,Liquido,ARIEL,...,128.047913,101.005630,13.297280,92.465370,97.479836,42.605934,141.207153,97.403450,123.509155,79.273132
14,10001,20001,0,38.0,214.723358,214.723358,HC,ROPA LAVADO,Liquido,ARIEL,...,101.207108,128.047913,101.005630,13.297280,89.776909,40.842865,148.724045,89.782318,114.308907,76.077293
15,10001,20001,0,23.0,133.450317,132.834183,HC,ROPA LAVADO,Liquido,ARIEL,...,43.339298,101.207108,128.047913,101.005630,117.594193,86.326965,136.286240,69.218941,124.497070,80.918388
16,10001,20001,0,21.0,165.735077,165.735077,HC,ROPA LAVADO,Liquido,ARIEL,...,289.350250,43.339298,101.207108,128.047913,145.332733,64.062401,121.406281,55.269093,134.458481,72.950172
17,10001,20001,0,33.0,92.294098,92.294098,HC,ROPA LAVADO,Liquido,ARIEL,...,222.113892,289.350250,43.339298,101.207108,171.097534,41.207115,130.437225,57.709442,139.852600,72.644196
18,10001,20001,0,40.0,257.536285,256.057587,HC,ROPA LAVADO,Liquido,ARIEL,...,111.549438,222.113892,289.350250,43.339298,130.287781,36.786648,123.940987,59.754322,136.873123,73.894829
19,10001,20001,0,23.0,139.242096,139.242096,HC,ROPA LAVADO,Liquido,ARIEL,...,131.271500,111.549438,222.113892,289.350250,171.362259,82.026634,158.347488,67.351349,149.777328,80.339935
20,10001,20001,0,54.0,358.579224,358.579224,HC,ROPA LAVADO,Liquido,ARIEL,...,49.618568,131.271500,111.549438,222.113892,162.531265,84.329170,166.814392,59.546524,157.769226,73.246193
21,10001,20001,0,22.0,248.171326,245.213974,HC,ROPA LAVADO,Liquido,ARIEL,...,88.440651,49.618568,131.271500,111.549438,251.292969,109.746162,190.790375,98.750534,163.538300,86.142982
22,10001,20001,0,19.0,246.939087,241.024384,HC,ROPA LAVADO,Liquido,ARIEL,...,214.723358,88.440651,49.618568,131.271500,247.678436,109.689331,209.520340,96.183655,165.463318,87.812866
23,10001,20001,0,20.0,254.623734,254.623734,HC,ROPA LAVADO,Liquido,ARIEL,...,132.834183,214.723358,88.440651,49.618568,281.605865,66.693794,222.068558,94.220047,176.252899,88.537560
24,10001,20001,0,53.0,393.260925,386.606873,HC,ROPA LAVADO,Liquido,ARIEL,...,165.735077,132.834183,214.723358,88.440651,246.954025,6.964655,249.123505,69.589790,186.532242,89.989174
25,10001,20001,0,39.0,309.906097,309.906097,HC,ROPA LAVADO,Liquido,ARIEL,...,92.294098,165.735077,132.834183,214.723358,294.084991,80.414291,270.881714,89.695900,214.614609,95.774185
26,10001,20001,0,23.0,142.871582,130.549271,HC,ROPA LAVADO,Liquido,ARIEL,...,256.057587,92.294098,165.735077,132.834183,317.045563,66.280586,299.325714,62.556080,233.070053,90.439835
27,10001,20001,0,33.0,364.370697,364.370697,HC,ROPA LAVADO,Liquido,ARIEL,...,139.242096,256.057587,92.294098,165.735077,275.687408,131.413712,261.320709,84.704842,226.055542,95.134583
28,10001,20001,0,31.0,439.906464,439.906464,HC,ROPA LAVADO,Liquido,ARIEL,...,358.579224,139.242096,256.057587,92.294098,268.275360,122.343590,281.180176,93.667534,245.350266,97.947067
29,10001,20001,0,7.0,65.924362,65.924362,HC,ROPA LAVADO,Liquido,ARIEL,...,245.213974,358.579224,139.242096,256.057587,311.608826,161.286484,314.327179,110.324280,268.197876,109.036804
30,10001,20001,0,14.0,144.787140,144.787140,HC,ROPA LAVADO,Liquido,ARIEL,...,241.024384,245.213974,358.579224,139.242096,290.067169,197.753418,282.877289,150.374283,266.000397,113.094398
31,10001,20001,0,9.0,33.639912,33.639912,HC,ROPA LAVADO,Liquido,ARIEL,...,254.623734,241.024384,245.213974,358.579224,216.872650,197.136734,242.574005,149.415558,256.727844,118.419823
32,10001,20001,0,18.0,111.516907,109.052437,HC,ROPA LAVADO,Liquido,ARIEL,...,386.606873,254.623734,241.024384,245.213974,81.450470,57.177109,196.529648,166.147156,247.927673,131.180588
33,10001,20001,0,21.0,178.494263,176.029800,HC,ROPA LAVADO,Liquido,ARIEL,...,309.906097,386.606873,254.623734,241.024384,95.826492,56.741703,192.946838,168.075119,227.133774,131.821411
34,10001,20001,0,21.0,240.598694,236.655563,HC,ROPA LAVADO,Liquido,ARIEL,...,130.549271,309.906097,386.606873,254.623734,106.240715,71.236572,161.556686,145.762970,221.368423,132.470093
35,10001,20001,0,18.0,214.721848,180.219376,HC,ROPA LAVADO,Liquido,ARIEL,...,364.370697,130.549271,309.906097,386.606873,173.912598,63.827904,127.681534,74.175888,221.004364,132.417160
28440,10002,20001,0,17.0,38.683010,35.728062,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28441,10002,20001,0,15.0,6.794150,6.794150,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28442,10002,20001,0,22.0,29.963659,29.941280,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28443,10002,20001,0,28.0,23.561260,22.811331,HC,ROPA LAVADO,Liquido,ARIEL,...,NaN,NaN,NaN,NaN,24.154497,15.310388,0.000000,0.000000,0.000000,0.000000

### hago unos casteos para optimizacion

In [5]:
# cast rápidos
df["sku_size"] = df["sku_size"].astype("int32")
df["periodo_indice"]  = df["periodo_indice"].astype("int16")
df["cust_request_qty"] = df["cust_request_qty"].astype("float32")

for col in ["cat1","cat2","cat3","brand"]:
    df[col] = df[col].astype("category")